# Gradle JVM settings
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.7
yarn_mappings=1.21.7+build.2
loader_version=0.16.14
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=2.0.0
maven_group=com.wh0oo.fortune
archives_base_name=fortune

# Dependencies
fabric_version=0.128.1+1.21.7
